version: '3'
services:
  db:
    image: mysql:5.7.24
    restart: always
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./sql:/docker-entrypoint-initdb.d/
    environment:
       MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:3306
  buy:
    image: registry.cn-hangzhou.aliyuncs.com/sxb-app/buy-limit:1.0
    restart: always
    container_name: buy-limit
    links:
    - db
    depends_on:
    - db
    ports:
    - 8080:8080  
